'''

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

'''

import time
start=time.time()
a=1
b=1
n=1
c=0
limit=4000000
suma=0
while c < limit:
    c=a+b
    b=a
    a=c
    n=n+1
    if c%2==0:
        suma=suma+c
print suma
end= time.time()
print end-start
